kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dind-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: sapdhinstall
spec:
  selector:
    matchLabels:
      app: sapdhinstall
  replicas: 1
  template:
    metadata:
      labels:
        app: sapdhinstall
    spec:
      containers:
      - image: "docker:dind"
        imagePullPolicy: IfNotPresent
        name: dind
        resources: 
            requests: 
                cpu: 20m 
                memory: 512Mi 
        securityContext: 
            privileged: true
        volumeMounts:
        - mountPath: /var/lib/docker
          name: dind-data
        - mountPath: /tmp
          name: dind-tmp
        - mountPath: /etc/docker/certs.d
          name: certs
        - mountPath: /root/SAPDHinstalls
          name: sapdhinstalls
      - image: "johnkday/sapdhinstall:latest"
        imagePullPolicy: Always
        name: sapdhinstall
        env: 
          - name: DOCKER_HOST 
            value: tcp://localhost:2375
        command: [ '/bin/bash', '-c', '--' ]
        args: [ "trap : TERM INT; sleep infinity & wait" ]
        volumeMounts:
        - mountPath: /etc/docker/certs.d
          name: certs
        - mountPath: /root/SAPDHinstalls
          name: sapdhinstalls
      restartPolicy: Always
      volumes:
      - name: dind-data
        persistentVolumeClaim:
          claimName: dind-vol
      - name: dind-tmp
        emptyDir: {}
      - name: certs
        emptyDir: {}
      - name: sapdhinstalls
        emptyDir: {}
